[variables]
PORT = "3002"
# SOLUCIÓN MAESTRA: Activamos el soporte nativo de require(ESM) oculto en Node 22.11.0
NODE_OPTIONS = "--experimental-require-module"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
# 1. Saltamos el bloqueo rígido de texto de Prisma usando --ignore-scripts
# 2. Recompilamos dependencias nativas como bcrypt de forma aislada
cmds = [
  "npm install --legacy-peer-deps --ignore-scripts",
  "npm rebuild bcrypt",
  "echo \"DATABASE_URL=${DATABASE_URL}\" > .env",
  "echo \"NEXTAUTH_URL=${NEXTAUTH_URL}\" >> .env",
  "echo \"NEXTAUTH_SECRET=${NEXTAUTH_SECRET}\" >> .env",
  "echo \"PORT=${PORT}\" >> .env",
  "echo \"NEXTAUTH_COOKIE_NAME=${NEXTAUTH_COOKIE_NAME}\" >> .env"
]

[phases.build]
# Gracias a NODE_OPTIONS, prisma generate interpretará zeptomatch sin crashear
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npx next start -H 0.0.0.0 -p 3002"
